name: Lint Test and Build
on: workflow_dispatch
jobs:
    lint:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Linters
              run: npm run lint
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run: npm ci
        - name: Test
          run: npm test
    build:
      needs: [lint, test]
      runs-on: ubuntu-latest
      outputs:
          version: ${{steps.build_version.outputs.version}}
          environment: ${{steps.env.outputs.environment}}

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run: npm ci
        - name: Build
          run: npm run build
        - name: Upload Build Files
          uses: actions/upload-artifact@v4
          with:
            name: Build Files
            path: dist
        - name: Get Version
          id: build_version
          run: |
            VERSION=$(git describe --tags --always)
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        - name: Print Version
          run : echo ${{steps.build_version.outputs.version}}
        - name: Env
          id: env  
          run: echo "environment=dev" >> "$GITHUB_OUTPUT"
    deploy:
      needs: build
      runs-on: ubuntu_latest
      steps:
        - name: Output Build Version and Environment
          run: echo Version = ${{needs.build.outputs.version}}, Env = ${{needs.build.outputs.environment}}
        - name: Download Artifactory
          uses: actions/download-artifact@v4
          with:
            name: Build Files
            path: dist
        - name: Deploy
          run: echo "Deploying...."
            