name: Lint Workflow
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Linters
              uses: wearerequired/lint-action@v3
              with:
                eslint: true
                prettier: true
            